### PR TITLE
Create the observatorium CSV

### PR DESCRIPTION
**Pull request by rthallisey**
This CSV is made with the assumption that only the obervatorium API
needs to be exposed to OLM.

WIP for now.  I'll do some additional testing on OCP tomorrow.

### CODE REVIEW

**Comment by rthallisey** [comment]
Didn't use https://github.com/operator-framework/operator-sdk/blob/master/doc/user/olm-catalog/generating-a-csv.md because this doesn't look like this is based on the operator-sdk, which is fine.

**Comment by rollandf** [comment]
Yes, we used kubebuilder here, not operator-sdk.

**Comment by rthallisey** [comment]
Sorry I've been neglecting this PR.  It's nearly complete, but I don't currently have the bandwidth the push it over the finish line.  The current status is the observatorium operator appears the ui, but when I subscribe, the deployment don't get launched.  Seems like I made a mistake somewhere in the CSV yaml, but didn't have a chance to pin down the issue.  Feel free to pickup where I left off, for now, I'm closing this PR.

**Comment by rollandf** [comment]
Thanks, we will pick it up.

**Pull request closed without merging**
